sudo: required
services:
  - docker
before_install:
  - docker build -t lucalmeida/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true lucalmeida/react-test npm run test
after_success:
  - docker build -t lucalmeida/multi-client ./client
  - docker build -t lucalmeida/multi-nginx ./nginx
  - docker build -t lucalmeida/multi-server ./server
  - docker build -t lucalmeida/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lucalmeida/multi-client
  - docker push lucameida/multi-nginx
  - docker push lucameida/multi-server
  - docker push lucameida/multi-worker
